site_name: uart-probe

site_author: Ben Marshall

theme: readthedocs

repo_name: https://github.com/ben-marshall/uart-probe

markdown_extensions:
- smarty
- sane_lists
- footnotes
- toc

pages:
- Specification: 
    - Overview: spec-overview.md
    - Details: spec-details.md
- Commands: command-list.md
- Integration: 
    - Overview: integration.md
    - FSM: rtl-fsm.md
- Probe: probe-program.md
