site_name: verilog-probe

site_author: Ben Marshall

theme: readthedocs

repo_name: https://github.com/ben-marshall/verilog-probe

markdown_extensions:
- smarty
- sane_lists
- footnotes
- toc

pages:
- VerilogProbe: README.md
- Probe: probe-program.md
- Specification: 
    - Overview: spec-overview.md
    - Details: spec-details.md
- Commands: command-list.md
- Integration: integration.md
