#!/usr/bin/python3


#
# Probe Command Encodings
#
#   These represent encoded versions of probe commands, and the actual data
#   we send to the probe to do stuff.
#

PROBE_CMD_RDGPI0 = 2   
PROBE_CMD_RDGPI1 = 3   
PROBE_CMD_RDGPI2 = 4   
PROBE_CMD_RDGPI3 = 5   
PROBE_CMD_RDGPO0 = 6   
PROBE_CMD_RDGPO1 = 7   
PROBE_CMD_RDGPO2 = 8   
PROBE_CMD_RDGPO3 = 9   
PROBE_CMD_WRGPO0 = 10  
PROBE_CMD_WRGPO1 = 11  
PROBE_CMD_WRGPO2 = 12  
PROBE_CMD_WRGPO3 = 13  
PROBE_CMD_RDAXA0 = 14  
PROBE_CMD_RDAXA1 = 15  
PROBE_CMD_RDAXA2 = 16  
PROBE_CMD_RDAXA3 = 17  
PROBE_CMD_WRAXA0 = 18  
PROBE_CMD_WRAXA1 = 19  
PROBE_CMD_WRAXA2 = 20  
PROBE_CMD_WRAXA3 = 21  
PROBE_CMD_RDAXD  = 22  
PROBE_CMD_WRAXD  = 23  
PROBE_CMD_AXRDCS = 24  
PROBE_CMD_AXWRCS = 25  

